### ISSUE TITLE
Conflict with Advanced Macros module

### ISSUE THREAD

**Issue by ctbritt** [ardittristan/VTTMacroEditor#9]
Pretty bad conflict with advanced macros module. Seems to create two macro editors, one blank and one using Acelib, but they stack on top of each other. Screen shot attached:
<img width="715" alt="Screen Shot 2021-12-21 at 6 58 41 PM" src="https://user-images.githubusercontent.com/4516034/147012756-5f2f619a-7e96-45bc-831c-f34311bf1d6c.png">

**Comment by ctbritt** [comment]
Basically makes Macro Editor unusable.

**Comment by thatlonelybugbear** [comment]
~~Maybe change line 7 of editor.js to `Hooks.on("documentSheetRegistrarInit", () => {` instead of `Hooks.on("init", () => {` 
as a quick fix.~~

**Comment by ardittristan** [comment]
using documentSheetRegristrarInit uses a library which gives functions that have already been implemented in V9. Advanced Macros should update to use the new document registration instead of using the hook which was the old way. I'll take a look at making a workaround that makes macro editor work with the current version of advanced macros though.
